### ISSUE TITLE
Remove `defineSupportCode` from step registration

### ISSUE THREAD

**Issue by aseeeem** [FlippieCoetser/Cucumber.Decorators#1]
Hey!

So I came across this implementation and I think its neat

Do you mind if I fork this to open a PR and remove the `defineSupportRequest` portion?

**Comment by FlippieCoetser** [comment]
@aseeeem you are welcome to open a PR. I am not sure if the code will work without the `defineSupportRequest` but if you get it working then I can also learn a thing or two.

**Comment by FlippieCoetser** [comment]
@aseeeem new version released, `defineSupportRequest` removed.
