### ISSUE TITLE
Cucumber 4 support?

### ISSUE THREAD

**Issue by KeithGillette** [FlippieCoetser/Cucumber.Decorators#2]
Does this library support Cucumber 4? From the `package.json`, it looks like this package is based on Cucumber 3.1, but [4.2.1 is the latest release](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md).

**Comment by FlippieCoetser** [comment]
@KeithGillette I will test and update the `package.json` . I see no reason for the decorator to fail. Thanks for the heads-up

**Comment by FlippieCoetser** [comment]
@KeithGillette new version released and tested. `defineSupportCode` has been removed in favour of the new cucumber implementation style.
